//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_FUTBOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campeonato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campeonato()
        {
            this.Encuentroes = new HashSet<Encuentro>();
            this.Posiciones = new HashSet<Posicione>();
        }
    
        public int id { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fin { get; set; }
        public int categoria { get; set; }
    
        public virtual Cat_Categoria Cat_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuentro> Encuentroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posicione> Posiciones { get; set; }
    }
}
