//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_FUTBOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Jugador()
        {
            this.Data_Encuentro_Jugador = new HashSet<Data_Encuentro_Jugador>();
        }
    
        public int id { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public System.DateTime fec_nacimiento { get; set; }
        public System.DateTime fec_registro { get; set; }
        public short dorsal { get; set; }
        public Nullable<int> equipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_Encuentro_Jugador> Data_Encuentro_Jugador { get; set; }
        public virtual Cat_Equipo Cat_Equipo { get; set; }
    }
}
