//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_FUTBOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Encuentro_Jugador
    {
        public int encuentro { get; set; }
        public int jugador { get; set; }
        public int goles_anotados { get; set; }
        public int tarjetas_amarillas { get; set; }
        public int tarjetas_rojas { get; set; }
        public int goles_recibidos { get; set; }
    
        public virtual Cat_Jugador Cat_Jugador { get; set; }
        public virtual Encuentro Encuentro1 { get; set; }
    }
}
