//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_FUTBOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuentro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encuentro()
        {
            this.Data_Encuentro_Jugador = new HashSet<Data_Encuentro_Jugador>();
        }
    
        public int id { get; set; }
        public System.DateTime fec_encuentro { get; set; }
        public System.TimeSpan hora_encuentro { get; set; }
        public short numero_campo { get; set; }
        public int campeonato { get; set; }
        public Nullable<int> equipo_local { get; set; }
        public Nullable<int> equipo_visita { get; set; }
        public Nullable<short> goles_local { get; set; }
        public Nullable<short> goles_visita { get; set; }
        public bool finalizado { get; set; }
    
        public virtual Campeonato Campeonato1 { get; set; }
        public virtual Cat_Equipo Cat_Equipo { get; set; }
        public virtual Cat_Equipo Cat_Equipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_Encuentro_Jugador> Data_Encuentro_Jugador { get; set; }
    }
}
