//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_FUTBOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicione
    {
        public int id { get; set; }
        public Nullable<int> campeonato { get; set; }
        public Nullable<int> equipo { get; set; }
        public Nullable<int> goles_favor { get; set; }
        public Nullable<int> goles_contra { get; set; }
        public Nullable<int> juegos_ganados { get; set; }
        public Nullable<int> juegos_perdidos { get; set; }
        public Nullable<int> juegos_empatados { get; set; }
        public Nullable<int> puntos { get; set; }
    
        public virtual Campeonato Campeonato1 { get; set; }
        public virtual Cat_Equipo Cat_Equipo { get; set; }
    }
}
