//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_FUTBOL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoccerTotalEntities : DbContext
    {
        public SoccerTotalEntities()
            : base("name=SoccerTotalEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campeonato> Campeonatoes { get; set; }
        public virtual DbSet<Cat_Categoria> Cat_Categoria { get; set; }
        public virtual DbSet<Cat_Equipo> Cat_Equipo { get; set; }
        public virtual DbSet<Cat_Jugador> Cat_Jugador { get; set; }
        public virtual DbSet<Data_Encuentro_Jugador> Data_Encuentro_Jugador { get; set; }
        public virtual DbSet<Encuentro> Encuentroes { get; set; }
        public virtual DbSet<Posicione> Posiciones { get; set; }
    }
}
